version: '3.1'

services:
  server:
    build: ../
    image: "hews/autoswatch:${BUILD_VERSION}"
    environment:
      - ENV=development
      - FLASK_APP=autoswatch:app
    ports:
      - 5000:5000
    volumes:
      - ../autoswatch:/app/autoswatch:ro
  guard:
    build: ../
    image: hews/autoswatch
    environment:
      - ENV=test-guard
    volumes:
      - ../autoswatch:/app/autoswatch:ro
      - ../tests:/app/tests:ro
